data/org.triertech.TrierBridge.desktop usr/share/applications
data/org.triertech.TrierBridge.metainfo.xml usr/share/metainfo
data/icons/hicolor/scalable/apps/org.triertech.TrierBridge.svg usr/share/icons/hicolor/scalable/apps
data/icons/hicolor/symbolic/apps/org.triertech.TrierBridge-symbolic.svg usr/share/icons/hicolor/symbolic/apps
NOTICE usr/share/doc/trier-bridge
data/catalog/concepts.json usr/share/trier-bridge/catalog
data/integrations/tb_nautilus.py usr/share/trier-bridge/integrations
